### ISSUE TITLE
Delimiter spelled wrong

### ISSUE THREAD

**Issue by Zyxok** [00100000spacebar/Intro-to-Java-Files#1]
in mailing label, spelled wrong

**Comment by 00100000spacebar** [comment]
alrighty I'll take a look

**Comment by ejhon1116** [comment]
you are so bad at coding aidan youre like the dumbest person who ever lived on the planet earth of course we can forget about the aliens who dumber than you

**Comment by 00100000spacebar** [comment]
Why thank you sexy, wanna fuck?
